### ISSUE TITLE
UNHuRD

### ISSUE THREAD

**Issue by sideshowtom** [w3ctag/societal-impact-questionnaire#5]
The Societal Impact questionnaire at
https://w3ctag.github.io/societal-impact-questionnaire/
should include questions about the designers/implementers thoughts on the proposed software/whatever use in relation to
https://en.wikipedia.org/wiki/Universal_Declaration_of_Human_Rights
and
https://en.wikipedia.org/wiki/Nuremberg_Code

**Comment by torgo** [comment]
Thanks - these and many other things are inspiring our work both here and with the [Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/).
